### ISSUE TITLE
标注文件中页面的height和width貌似全反了

### ISSUE THREAD

**Issue by RDSJC** [opendatalab/OmniDocBench#5]

**Comment by wangbinDL** [comment]
Thank you for your feedback. We've identified an issue with the data export where the height and width were swapped on some pages. We'll fix this and update the dataset as soon as possible. Thank you for bringing this to our attention.

**Comment by ouyanglinke** [comment]
Thank you for your feedback. We have corrected the height and width of some samples, which only affects the page-level height and width fields and does not impact the accuracy of other annotations. The datasets on [Hugging Face](https://huggingface.co/datasets/opendatalab/OmniDocBench) and [OpenDataLab](https://opendatalab.com/OpenDataLab/OmniDocBench) have been updated accordingly.

**Comment by RDSJC** [comment]
还是有很多错误的height和width，虽然不会对指标结果产生影响，但是会影响可视化

**Comment by ouyanglinke** [comment]
We have double-checked the dataset and found no further issues with image width and height. Our dataset includes some landscape images (such as slides), where the width is indeed greater than the height. Please verify if this might have caused any misunderstanding. 
If you still encounter any issues with image dimensions, please kindly provide the specific image names for us to further confirm. Thank you for your feedback. 
Moreover, for visualization of OmniDocBench, you could refer to [visualization](https://github.com/opendatalab/OmniDocBench/blob/main/tools/visualization.py).

**Comment by RDSJC** [comment]
在colorful_textbook，exam_paper，magazine，newspaper存在问题，下面是一些badcase
![企业微信截图_17343167317004](https://github.com/user-attachments/assets/f3433d92-0eac-4338-9458-8f53919cd38a)

**Comment by ouyanglinke** [comment]
From your visualization results, it seems that there is an issue with the scaling ratio in your visualization code. Please refer to the [visualization](https://github.com/opendatalab/OmniDocBench/blob/main/tools/visualization.py) code provided in this repo. Below are the visualization results for the three cases you provided.
![image](https://github.com/user-attachments/assets/0d329ad7-979d-464c-a78d-aeecc1d5c5ec)
